language: java
jdk:
 - oraclejdk8

branches:
 only:
 - master

before_script:
 - cd ./MIFImageEditor
 - chmod +x ./gradlew

script:
 - ./gradlew assemble
 - ./gradlew check

env:
- TERM=dumb

after_success:
- ./gradlew jacocoTestReport coveralls